FROM jekyll/jekyll
MAINTAINER Robie Lutsey <robie1373@gmail.com>

RUN git config --global user.email robie1373@gmail.com
RUN git config --global user.name Robie
RUN git config --global push.default simple

WORKDIR /blog

ENTRYPOINT ["/bin/bash"]
